export const taskData = [
  {
    id: 0,
    name: "Parking Lot Decking",
    assignees: ["1345709545446"],
    dueDate: "2024-04-18",
    status: "IN-PROGRESS",
    priority: "HIGH",
    selectedSubtasks: 0,
    subTasksList: [
      {
        id: 1,
        name: "Foundation Preparation",
        assignees: ["1345709545446"],
        dueDate: "2024-04-10",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
      {
        id: 2,
        name: "Waterproofing Layer",
        assignees: ["1345709545446"],
        dueDate: "2024-04-15",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
      {
        id: 3,
        name: "Surface Finishing",
        assignees: ["1345709545446"],
        dueDate: "2024-04-18",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
    ],
  },
  {
    id: 1,
    name: "Ground Floor Fill",
    assignees: ["5440754979771"],
    dueDate: "2024-05-11",
    status: "COMPLETED",
    priority: "NORMAL",
    selectedSubtasks: 0,
    subTasksList: [
      {
        id: 4,
        name: "Ground Preparation",
        assignees: ["5440754979771"],
        dueDate: "2024-05-05",
        status: "COMPLETED",
        priority: "NORMAL",
        selected: false,
      },
      {
        id: 5,
        name: "Concrete Filling",
        assignees: ["5440754979771"],
        dueDate: "2024-05-11",
        status: "COMPLETED",
        priority: "NORMAL",
        selected: false,
      },
    ],
  },
  {
    id: 2,
    name: "Roofing Sheets Stack",
    assignees: ["1234567894543"],
    dueDate: "2024-04-20",
    status: "IN-PROGRESS",
    priority: "NORMAL",
    selectedSubtasks: 0,
    subTasksList: [],
  },
  {
    id: 3,
    name: "Electrical System Installation",
    assignees: ["8876543210"],
    dueDate: "2024-05-30",
    status: "IN-PROGRESS",
    priority: "HIGH",
    selectedSubtasks: 0,
    subTasksList: [
      {
        id: 6,
        name: "Main Panel Installation",
        assignees: ["8876543210"],
        dueDate: "2024-05-15",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
      {
        id: 7,
        name: "Wiring Layout",
        assignees: ["8876543210"],
        dueDate: "2024-05-20",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
      {
        id: 8,
        name: "Fixture Installation",
        assignees: ["8876543210"],
        dueDate: "2024-05-25",
        status: "IN-PROGRESS",
        priority: "NORMAL",
        selected: false,
      },
      {
        id: 9,
        name: "Testing and Certification",
        assignees: ["8876543210"],
        dueDate: "2024-05-30",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
    ],
  },
  {
    id: 4,
    name: "Window Installation",
    assignees: ["9987654321"],
    dueDate: "2024-04-25",
    status: "IN-PROGRESS",
    priority: "NORMAL",
    selectedSubtasks: 0,
    subTasksList: [],
  },
  {
    id: 5,
    name: "HVAC System Setup",
    assignees: ["2233445566"],
    dueDate: "2024-06-15",
    status: "IN-PROGRESS",
    priority: "HIGH",
    selectedSubtasks: 0,
    subTasksList: [
      {
        id: 10,
        name: "Ductwork Installation",
        assignees: ["2233445566"],
        dueDate: "2024-05-30",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
      {
        id: 11,
        name: "Unit Placement",
        assignees: ["2233445566"],
        dueDate: "2024-06-05",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
      {
        id: 12,
        name: "System Testing",
        assignees: ["2233445566"],
        dueDate: "2024-06-15",
        status: "IN-PROGRESS",
        priority: "HIGH",
        selected: false,
      },
    ],
  },
  {
    id: 6,
    name: "Interior Painting",
    assignees: ["3344556677"],
    dueDate: "2024-04-30",
    status: "IN-PROGRESS",
    priority: "NORMAL",
    selectedSubtasks: 0,
    subTasksList: [],
  },
];
